name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.2
          bundler-cache: true  # Changed to true to cache dependencies

      - name: Install dependencies
        run: bundle install

      - name: Run RuboCop
        run: bundle exec rubocop -f github

  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_PASSWORD: password
          POSTGRES_USER: postgres
          POSTGRES_DB: bscf_virtual_account_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.2
          bundler-cache: true

      - name: Setup test database
        env:
          RAILS_ENV: test
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          POSTGRES_PASSWORD: password
          POSTGRES_USER: postgres
          DATABASE_URL: "postgres://postgres:password@localhost:5432/bscf_virtual_account_test"
        run: |
          cp config/database.yml.ci config/database.yml || true
          bundle exec rails db:create db:schema:load

      - name: Run tests
        env:
          RAILS_ENV: test
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          POSTGRES_PASSWORD: password
          POSTGRES_USER: postgres
          DATABASE_URL: "postgres://postgres:password@localhost:5432/bscf_virtual_account_test"
        run: bundle exec rspec
